{% set name = "types-influxdb-client" %}
{% set version = "1.45.0.20240814" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-influxdb-client-{{ version }}.tar.gz
    sha256: 27d89f38b39ac16f5e120ec8ab12ae1d94bb5ccda045b5d70f193efb083aedef
  - url: https://github.com/python/typeshed/raw/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe
    path: LICENSE

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - urllib3 >=2

test:
  commands:
    - test -f $SP_DIR/influxdb_client-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for influxdb-client
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - conda-forge/mypy
