{% set name = "types-influxdb-client" %}
{% set version = "1.45.0.20240907" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-influxdb-client-{{ version }}.tar.gz
    sha256: eccd8b4d9611bc15765271878a3e48123b202f71cce2704fc6594f4937ca9b24
  - url: https://github.com/python/typeshed/raw/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe
    path: LICENSE

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - urllib3 >=2

test:
  commands:
    - test -f $SP_DIR/influxdb_client-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for influxdb-client
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - conda-forge/mypy
